### ISSUE TITLE
Add support for Android?

### ISSUE THREAD

**Issue by dhirendrarathod2000** [react-native-community/react-native-safe-area-view#21]
When i set my status bar in android app gets rendered under the status bar.
Also now a days we are getting android phones with notches and all that.

So does it make sense to add support for android?
it could be the matter of just returning `StatusBar.currentHeight` instead of `0`

Does it sound like a good idea?

**Comment by wahello** [comment]
Android need safe area toooo.

**Comment by pribeh** [comment]
This is increasingly becoming a problem now that more and more Android devices are being designed akin to the X.

**Comment by andrictham** [comment]
This is a problem with the Pixel 3 XL and the OnePlus 6. 

Android 9.0 [has a way to handle screen cutouts](https://proandroiddev.com/making-notch-friendly-apps-for-android-75776272be5c), but I can’t find any Expo-friendly components to deal with this.

**Comment by VinceBT** [comment]
Would #52 fix the issue ?

**Comment by brentvatne** [comment]
yeah this is really bad that it doesn't exist here yet. i was hoping https://github.com/facebook/react-native/pull/20999 would land much sooner and we'd be able to leverage this api, but it's taking a while. i'll see if there are any temporary workarounds

**Comment by LaszloDev** [comment]
Look like https://github.com/th3rdwave/react-native-safe-area-context will do the job for now. Its already added to the upcoming Expo SDK 35: https://github.com/expo/expo/issues/5424

**Comment by brentvatne** [comment]
@LaszloDev yup! in sdk35 you can use the 1.0-alpha version of this repo as well, which uses react-native-safe-area-context

**Comment by SimenB** [comment]
Will this support going behind the new navigation bar in Android 10, which is the suggested way?

https://medium.com/androiddevelopers/gesture-navigation-going-edge-to-edge-812f62e4e83e

>The first, and most important consideration for supporting gesture navigation, is drawing behind the navigation bar. Since the navigation bar has shrunk in size and prominence, it is now _strongly_ recommended for apps to draw behind the navigation bar when running on Android Q+ for a more compelling and modern UX.

I tried adding this module to an Expo 35 project, but it doesn't go behind the navigation bar (it does go behind the notch though, but that worked previously as well)

**Comment by brentvatne** [comment]
@SimenB - can you demonstrate what you're saying about adding this to an expo sdk 35 project re: notch and navigation bar with a code example and screenshots?

**Comment by SimenB** [comment]
You can see it in the expo app itself - the navigation bar is on black background rather than covering the background which goes against Google's recommendations I linked above.

![Screenshot_20190926-113757](https://user-images.githubusercontent.com/1404810/65677600-33a67d80-e052-11e9-937e-f2eb2e81ab41.png)
Compare to e.g play store:

![Screenshot_20190926-114028](https://user-images.githubusercontent.com/1404810/65677767-7ec09080-e052-11e9-9597-6a6c3edaff6a.png)

As for code, I just added this module to full size white background, and I still got a black bar at the bottom - notch at the top worked great. Currently on mobile, so hard to get a code example up

**Comment by LaszloDev** [comment]
~~I can confirm that with Expo 35 the Android statusbar is grey instead of transparent. Reproduce with `expo init` and `tabs`-template.~~ 
Edit: The background color of the view does have an effect on the color of the status bar as it translucent per default and not fully transparent. @SimenB try to open the React-Navigation demo in your client. 
![Screenshot_1569506060](https://user-images.githubusercontent.com/10655255/65694310-f48a2380-e075-11e9-8d73-3468ee2abb57.png)

~~But regards what @SimenB said, my statusbar looks way slimmer then his screenshot.~~ 
Edit: Not having a display cutout creates a smaller statusbar.

expo: 35.0.0
expo client: 2.13.0 
Android (Simulator): Pixel 3A with Android 10

**Comment by brentvatne** [comment]
that behavior is unrelated to this library, the purpose of this library is to be able to inset your views when the content is already rendered underneath the status bar / notch or bottom OS navigation UI.

we don't expose an api in expo managed workflow for doing edge-to-edge on devices with notches currently, but that's an issue for the expo/expo repo

**Comment by brentvatne** [comment]
support for android in this library is available in 1.0.0 which i just released, see the readme for more info

**Comment by SimenB** [comment]
Opened up https://expo.canny.io/feature-requests/p/edge-to-edge-support-for-android for edge-to-edge, unless you think I should open it on expo/expo @brentvatne?

**Comment by brentvatne** [comment]
thanks @SimenB, i'll discuss this internally and hopefully we can find time to add it very soon
