### ISSUE TITLE
ListView seems to remove the padding

### ISSUE THREAD

**Issue by anthonywhiteman** [react-native-community/react-native-safe-area-view#6]
Having a ListView inside of a SafeAreaView seems to break the component. 

Something as simple as 

`<SafeAreaView>
    <ListView
        dataSource={ dataSource }
        renderRow={ (rowData) => <Text>{rowData.name}</Text> }
    />
</SafeAreaView>`

Does not work as expected.

**Comment by davepack** [comment]
Any List type view that inherits from ScrollView should use the [contentInsetAdjustment prop](https://facebook.github.io/react-native/docs/scrollview.html#contentinsetadjustmentbehavior) to have safe area insets on the view, rather than wrapping in SafeAreaView. This includes ListView, FlatList, etc.
