### ISSUE TITLE
Difference between your component and built-in component

### ISSUE THREAD

**Issue by imcvampire** [react-native-community/react-native-safe-area-view#94]
# Question

Hi, 

Can you share me what is the difference between your component and the built-in component https://facebook.github.io/react-native/docs/safeareaview

Thank you!

**Comment by thinklinux** [comment]
From what I can see in the readme is way more flexible. But I would like to know more too! :))

**Comment by wangzuo** [comment]
I guess you cannot get inset values with built-in component.

**Comment by nelsonprsousa** [comment]
I also didn't get it. For now I'll use the built-in component since I didn't encounter any problem (at least, yet).

Maybe someone can add some inputs? I am sure this can be useful somehow 👍

**Comment by pvinis** [comment]
It would be helpful to have a couple of comparisons in the readme, maybe on specific cases or choices/decisions.

**Comment by brentvatne** [comment]
don't use this library and don't use the built in SafeAreaView, use SafeAreaView from https://github.com/th3rdwave/react-native-safe-area-context instead.

this library was made so that we could support safe areas in react-navigation immediately upon iphone x launch without depending on users upgrading to a version of react-native that would support it. later, it served as a more flexible alternative because you could programmatically get insets. now, react-native-safe-area-context provides everything you need from core and this library and in a far superior way to both. please use it instead.

we plan to deprecate this library soon.

**Comment by adbl** [comment]
@brentvatne is this library considered deprecated now?

**Comment by brentvatne** [comment]
i think it's fair to treat it as deprecated, yeah. [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context) was built in order to replace it and it does a much better job

**Comment by adbl** [comment]
Thanks! I suggest to include a notice about this in the README.

**Comment by brentvatne** [comment]
@adbl - i did that right after responding :) i totally agree. https://github.com/react-navigation/react-native-safe-area-view/commit/07011a264fff3d318c69434f9022aa114435770f

**Comment by adbl** [comment]
Great thanks!
